/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramTagRouteImport } from './routes/api/public/telegram/tag'
import { Route as ApiPublicTelegramStatusRouteImport } from './routes/api/public/telegram/status'
import { Route as ApiPublicTelegramMessagesRouteImport } from './routes/api/public/telegram/messages'

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramTagRoute = ApiPublicTelegramTagRouteImport.update({
  id: '/api/public/telegram/tag',
  path: '/api/public/telegram/tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramStatusRoute = ApiPublicTelegramStatusRouteImport.update({
  id: '/api/public/telegram/status',
  path: '/api/public/telegram/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramMessagesRoute =
  ApiPublicTelegramMessagesRouteImport.update({
    id: '/api/public/telegram/messages',
    path: '/api/public/telegram/messages',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/import': typeof ImportRoute
  '/api/public/telegram/messages': typeof ApiPublicTelegramMessagesRoute
  '/api/public/telegram/status': typeof ApiPublicTelegramStatusRoute
  '/api/public/telegram/tag': typeof ApiPublicTelegramTagRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/import': typeof ImportRoute
  '/api/public/telegram/messages': typeof ApiPublicTelegramMessagesRoute
  '/api/public/telegram/status': typeof ApiPublicTelegramStatusRoute
  '/api/public/telegram/tag': typeof ApiPublicTelegramTagRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/import': typeof ImportRoute
  '/api/public/telegram/messages': typeof ApiPublicTelegramMessagesRoute
  '/api/public/telegram/status': typeof ApiPublicTelegramStatusRoute
  '/api/public/telegram/tag': typeof ApiPublicTelegramTagRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/import'
    | '/api/public/telegram/messages'
    | '/api/public/telegram/status'
    | '/api/public/telegram/tag'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/import'
    | '/api/public/telegram/messages'
    | '/api/public/telegram/status'
    | '/api/public/telegram/tag'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/import'
    | '/api/public/telegram/messages'
    | '/api/public/telegram/status'
    | '/api/public/telegram/tag'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ImportRoute: typeof ImportRoute
  ApiPublicTelegramMessagesRoute: typeof ApiPublicTelegramMessagesRoute
  ApiPublicTelegramStatusRoute: typeof ApiPublicTelegramStatusRoute
  ApiPublicTelegramTagRoute: typeof ApiPublicTelegramTagRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/tag': {
      id: '/api/public/telegram/tag'
      path: '/api/public/telegram/tag'
      fullPath: '/api/public/telegram/tag'
      preLoaderRoute: typeof ApiPublicTelegramTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/status': {
      id: '/api/public/telegram/status'
      path: '/api/public/telegram/status'
      fullPath: '/api/public/telegram/status'
      preLoaderRoute: typeof ApiPublicTelegramStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/messages': {
      id: '/api/public/telegram/messages'
      path: '/api/public/telegram/messages'
      fullPath: '/api/public/telegram/messages'
      preLoaderRoute: typeof ApiPublicTelegramMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ImportRoute: ImportRoute,
  ApiPublicTelegramMessagesRoute: ApiPublicTelegramMessagesRoute,
  ApiPublicTelegramStatusRoute: ApiPublicTelegramStatusRoute,
  ApiPublicTelegramTagRoute: ApiPublicTelegramTagRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
